### ISSUE TITLE
Motion Detector Issue

### ISSUE THREAD

**Issue by farberm** [donhoffman/indigo-caddx-plugin#4]
The plugin installed without issues and all old items were there. I am getting the following error however for the motion detector.

Aug 23, 2022 at 11:19:17 PM
   Caddx Security System           -- create variable: description : 
folderId : 1894940605
globalProps : MetaProps : (dict)
id : 1988356459
name : partitionState
pluginProps : com.ians.caddx : (dict)
readOnly : False
remoteDisplay : True
sharedProps : com.indigodomo.indigoserver : (dict)
value : : 
   Error                           device "Caddx_zone 005 - MOTION DETECTOR" state key onOffState not defined (ignoring update request)

**Comment by donhoffman** [comment]
Due to my use of wrong base version for port.
